default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: trailing-whitespace
        files: '^(about/|blog/|projects/)' 
      - id: end-of-file-fixer
        files: '^(about/|blog/|projects/)' 
      - id: check-docstring-first
        files: '^(about/|blog/|projects/)' 
      - id: check-yaml
        files: '^(about/|blog/|projects/)' 
      - id: debug-statements
        files: '^(about/|blog/|projects/)' 
      - id: detect-private-key
        files: '^(about/|blog/|projects/)' 
      - id: check-executables-have-shebangs
        files: '^(about/|blog/|projects/)' 
      - id: check-toml
        files: '^(about/|blog/|projects/)' 
      - id: check-case-conflict
        files: '^(about/|blog/|projects/)' 
      - id: check-added-large-files
        args: ['--maxkb=30000']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
      - id: ruff-format
