project:
  type: website

website:
  title: "AI Intuition"
  site-url: https://www.ai-intuition.com
  search:
    location: navbar
    type: textbox
  page-navigation: true
  navbar:
    left:
      - text: Projects
        href: projects/index.qmd
      - text: Blog
        href: blog/index.qmd
    right:
      - about/index.qmd
      - icon: github
        href: https://github.com/charleneleong-ai/
      - icon: linkedin
        href: https://www.linkedin.com/in/charleneleong/
  favicon: favicon.png
  open-graph: true
  body-footer: 
      <!-- 100% privacy-first analytics -->
      <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
      <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
      

format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: kable
    csl: styles/ieee.csl
    page-layout: full
    fig-cap-location: bottom
    crossrefs-hover: true

editor: visual
